export const deals = [
  {
    id: "deal-1",
    dealName: "Website Redesign",
    client: "Acme Corp",
    owner: "Alex Ray",
    ownerInitials: "AR",
    dealInitial: "W",
    dealColor: "bg-[#6e3ff3]",
    stage: "Negotiation",
    value: 15000,
    expectedClose: "2026-03-12",
  },
  {
    id: "deal-2",
    dealName: "Mobile App",
    client: "Beta LLC",
    owner: "Mina Swan",
    ownerInitials: "MS",
    dealInitial: "M",
    dealColor: "bg-[#df3674]",
    stage: "Proposal Sent",
    value: 8000,
    expectedClose: "2026-04-01",
  },
  {
    id: "deal-3",
    dealName: "Integration Work",
    client: "Gamma Inc",
    owner: "John Kim",
    ownerInitials: "JK",
    dealInitial: "I",
    dealColor: "bg-[#00b894]",
    stage: "Qualified",
    value: 12000,
    expectedClose: "2026-05-20",
  },
  {
    id: "deal-4",
    dealName: "Marketing Retainer",
    client: "Delta Co",
    owner: "Sarah Lee",
    ownerInitials: "SL",
    dealInitial: "M",
    dealColor: "bg-[#fdba74]",
    stage: "Discovery",
    value: 5000,
    expectedClose: "2026-02-28",
  },
  {
    id: "deal-5",
    dealName: "Data Migration",
    client: "Epsilon Ltd",
    owner: "Alex Ray",
    ownerInitials: "AR",
    dealInitial: "D",
    dealColor: "bg-[#6e3ff3]",
    stage: "Negotiation",
    value: 22000,
    expectedClose: "2026-06-10",
  },
  {
    id: "deal-6",
    dealName: "Security Audit",
    client: "Zeta Partners",
    owner: "Mina Swan",
    ownerInitials: "MS",
    dealInitial: "S",
    dealColor: "bg-[#df3674]",
    stage: "Proposal Sent",
    value: 18000,
    expectedClose: "2026-03-30",
  },
  {
    id: "deal-7",
    dealName: "Cloud Setup",
    client: "Eta Group",
    owner: "John Kim",
    ownerInitials: "JK",
    dealInitial: "C",
    dealColor: "bg-[#00b894]",
    stage: "Qualified",
    value: 27000,
    expectedClose: "2026-07-05",
  },
  {
    id: "deal-8",
    dealName: "SEO Package",
    client: "Theta Studios",
    owner: "Sarah Lee",
    ownerInitials: "SL",
    dealInitial: "S",
    dealColor: "bg-[#fdba74]",
    stage: "Discovery",
    value: 3000,
    expectedClose: "2026-02-20",
  },
  {
    id: "deal-9",
    dealName: "Support Contract",
    client: "Iota Services",
    owner: "Alex Ray",
    ownerInitials: "AR",
    dealInitial: "S",
    dealColor: "bg-[#6e3ff3]",
    stage: "Negotiation",
    value: 6000,
    expectedClose: "2026-04-18",
  },
  {
    id: "deal-10",
    dealName: "Analytics",
    client: "Kappa Digital",
    owner: "Mina Swan",
    ownerInitials: "MS",
    dealInitial: "A",
    dealColor: "bg-[#df3674]",
    stage: "Proposal Sent",
    value: 14000,
    expectedClose: "2026-05-01",
  },
];
